[package]
edition = "2021"
license = "MIT"
name = "getting-started"

[[bin]]
name = "routeguide-server"
path = "src/server/server.rs"

[[bin]]
name = "routeguide-client"
path = "src/client/client.rs"

[dependencies]
# Common dependencies
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }
protobuf = "4.35.1-release"
grpc = { git = "https://github.com/grpc/grpc-rust.git", rev = "0761f5507a13540dbb509d47d7ca672d28b151e8", package = "grpc" }
grpc-protobuf = { git = "https://github.com/grpc/grpc-rust.git", rev = "0761f5507a13540dbb509d47d7ca672d28b151e8", package = "grpc-protobuf" }
tonic = { git = "https://github.com/grpc/grpc-rust.git", rev = "0761f5507a13540dbb509d47d7ca672d28b151e8", package = "tonic" }
tonic-protobuf = { git = "https://github.com/grpc/grpc-rust.git", rev = "0761f5507a13540dbb509d47d7ca672d28b151e8", package = "tonic-protobuf" }

# Server JSON data loading dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
grpc-protobuf-build = { git = "https://github.com/grpc/grpc-rust.git", rev = "0761f5507a13540dbb509d47d7ca672d28b151e8", package = "grpc-protobuf-build", default-features = false }

[features]
regenerate_proto = ["grpc-protobuf-build/protoc-gen-rust-grpc"]

